// GENERATED approved copy for the "brands" page, from docs/design/handoff/Platform Mockups.dc.html.
// Staff edits are stored in settings (content.brands) and override these by key.
export const brandsContent: Record<string, string> = {
  "brands.001": "For creators",
  "brands.002": "For brands",
  "brands.003": "Case studies",
  "brands.004": "Pricing",
  "brands.005": "Book a call",
  "brands.006": "↗",
  "brands.007": "1B+ VIEWS DELIVERED",
  "brands.008": "Reach that ads can’t buy.",
  "brands.009": "Clips on every feed, at scale.",
  "brands.010": "A network of clippers turns your best moments into short videos across TikTok, Reels and Shorts, so your brand shows up where attention already is.",
  "brands.011": "Book a call",
  "brands.012": "→",
  "brands.013": "See the results",
  "brands.014": "Clips built to travel",
  "brands.015": "Short, native videos made for every feed.",
  "brands.016": "Pay for what counts",
  "brands.017": "Only views that pass review are paid.",
  "brands.018": "CLIP MORE · PAY PER VIEW ·",
  "brands.019": "1B+ views generated for",
  "brands.020": "the biggest brands and",
  "brands.021": "artists in the world.",
  "brands.022": "Less guesswork.",
  "brands.023": "More views.",
  "brands.024": "CAMPAIGNS DELIVERED FOR",
  "brands.025": "Music",
  "brands.026": "Gaming",
  "brands.027": "Retail",
  "brands.028": "Film and TV",
  "brands.029": "Live events",
  "brands.030": "Sports",
  "brands.031": "Music",
  "brands.032": "Gaming",
  "brands.033": "Retail",
  "brands.034": "Film and TV",
  "brands.035": "Live events",
  "brands.036": "Sports",
  "brands.037": "Music",
  "brands.038": "Gaming",
  "brands.039": "Retail",
  "brands.040": "Film and TV",
  "brands.041": "Live events",
  "brands.042": "Sports",
  "brands.043": "Music",
  "brands.044": "Gaming",
  "brands.045": "Retail",
  "brands.046": "Film and TV",
  "brands.047": "Live events",
  "brands.048": "Sports",
  "brands.049": "The network",
  "brands.050": "A clipping network built for",
  "brands.051": "reach",
  "brands.052": ", not roster limits",
  "brands.053": "Instead of booking a fixed roster, brands plug into a network of clippers who choose campaigns that fit their audience and style. Distribution scales without mismatched placements or inflated media pricing.",
  "brands.054": "Brands plug in. Clippers post. You pay for",
  "brands.055": "counted views",
  "brands.056": ".",
  "brands.057": "LIVE ON EVERY FEED",
  "brands.058": "Music and releases",
  "brands.059": "Sports highlights",
  "brands.060": "Gaming clips",
  "brands.061": "Film and TV",
  "brands.062": "Retail",
  "brands.063": "Podcasts",
  "brands.064": "Live streams",
  "brands.065": "Streamer clips",
  "brands.066": "UGC",
  "brands.067": "Lifestyle",
  "brands.068": "Brand launches",
  "brands.069": "+ many more",
  "brands.070": "Industries",
  "brands.071": "Built for the brands that need reach most",
  "brands.072": "Release cycles, product launches and live moments all move faster when clips are already on every feed.",
  "brands.073": "Music and artists",
  "brands.074": "Releases that travel",
  "brands.075": "Labels and artists put tracks, videos and moments in front of new audiences. Clippers turn a release into clips that live on every feed.",
  "brands.076": "Sound promos",
  "brands.077": "Release clips",
  "brands.078": "Live performance",
  "brands.079": "Tour content",
  "brands.080": "Brands and launches",
  "brands.081": "Awareness at scale",
  "brands.082": "Retail, gaming and consumer brands get their product and content shown across feeds, with every counted view tracked.",
  "brands.083": "Product launches",
  "brands.084": "Gaming clips",
  "brands.085": "Brand moments",
  "brands.086": "UGC",
  "brands.087": "Process",
  "brands.088": "How it works",
  "brands.089": "You set the goal. We run the network.",
  "brands.090": "01",
  "brands.091": "Brief and strategy",
  "brands.092": "Work with our team to define your niche, content, rate per 1,000 views and budget.",
  "brands.093": "02",
  "brands.094": "Clippers activate",
  "brands.095": "Your campaign goes live to the network. Clippers choose it based on fit and audience.",
  "brands.096": "03",
  "brands.097": "Review before it counts",
  "brands.098": "Every post is checked before it counts, and every approved post links to its source.",
  "brands.099": "04",
  "brands.100": "Pay for counted views",
  "brands.101": "You pay only for views that pass review. Posts keep working after the budget is spent.",
  "brands.102": "Why Maison d’Élites",
  "brands.103": "The unfair advantage",
  "brands.104": "Clipping scale, clear reporting and per-view pricing in one channel built for measurable distribution.",
  "brands.105": "Pay only for counted views",
  "brands.106": "Your spend follows verified views, not estimates or promises.",
  "brands.107": "Clips in every niche",
  "brands.108": "Music, sports, gaming, retail and more. Clippers pick campaigns that fit their audience.",
  "brands.109": "Content that keeps working",
  "brands.110": "When the budget is spent, the posts stay live and keep earning views.",
  "brands.111": "Full transparency",
  "brands.112": "A live dashboard with a direct link to every approved post. No guesswork.",
  "brands.113": "Zero operational lift",
  "brands.114": "We handle clipper outreach, briefing, review and payouts.",
  "brands.115": "Rules and approvals you control",
  "brands.116": "Set the rules, the rate and the budget. Nothing counts until it passes review.",
  "brands.117": "Case studies",
  "brands.118": "Numbers that don’t lie",
  "brands.119": "Over 1B views delivered. Proof for every campaign below.",
  "brands.120": "CASE STUDY",
  "brands.121": "/",
  "brands.122": "Maison d’Élites",
  "brands.123": "CLIPPING",
  "brands.124": "OBJECTIVE",
  "brands.125": "STRATEGY",
  "brands.126": "RESULT",
  "brands.127": "PERFORMANCE SUMMARY",
  "brands.128": "Kojo Blak",
  "brands.129": "In his words",
  "brands.130": "Hear it from",
  "brands.131": "Kojo Blak.",
  "brands.132": "His testimonial on working with Maison d’Élites.",
  "brands.133": "Kojo Blak",
  "brands.134": "Artist",
  "brands.135": "Recommends Maison d’Élites",
  "brands.136": "Later won Best New Ghanaian Artist",
  "brands.137": "Pricing",
  "brands.138": "Simple. Performance-based.",
  "brands.139": "Only pay for verified views delivered, not performance estimates. Larger spend commitments unlock lower fees.",
  "brands.140": "Starter",
  "brands.141": "$3K to $10K",
  "brands.142": "A low-friction entry point for sound promos, logo placements and first campaigns on the network.",
  "brands.143": "Sound promo or logo placement",
  "brands.144": "Live campaign dashboard",
  "brands.145": "Automated content moderation",
  "brands.146": "Verified-view billing",
  "brands.147": "Book a call",
  "brands.148": "MOST POPULAR",
  "brands.149": "Growth",
  "brands.150": "$10K to $50K",
  "brands.151": "Recurring campaigns with broader targeting, creative support and better commercial terms as volume scales.",
  "brands.152": "Geo-targeted or worldwide campaigns",
  "brands.153": "Sports and entertainment audience targeting",
  "brands.154": "Free animated logo creative",
  "brands.155": "Lower fees at higher volume",
  "brands.156": "Dedicated niche expert",
  "brands.157": "Dedicated fan pages",
  "brands.158": "Book a call",
  "brands.159": "Scale",
  "brands.160": "Custom",
  "brands.161": "Custom commercial structure for brands buying at serious volume across multiple niches, markets or campaign waves.",
  "brands.162": "Dedicated strategic support",
  "brands.163": "Enterprise reporting and brand controls",
  "brands.164": "Multi-segment campaign strategy",
  "brands.165": "Volume-based pricing",
  "brands.166": "Priority clipper allocation",
  "brands.167": "Dedicated fan pages",
  "brands.168": "Book a call",
  "brands.169": "Put your content",
  "brands.170": "to work.",
  "brands.171": "BUILT FOR REACH. PAID FOR VIEWS.",
  "brands.172": "Walmart, Nintendo, WYDE, Sony and DEF JAM have run campaigns through our network.",
  "brands.173": "Book a call",
  "brands.174": "→",
  "brands.175": "Legal",
  "brands.176": "Privacy Policy",
  "brands.177": "Creator Terms of Use",
  "brands.178": "Brand Terms of Use",
  "brands.179": "Company",
  "brands.180": "Contact Us",
  "brands.181": "Support",
  "brands.182": "Careers",
  "brands.183": "© 2026 Maison d’Élites. All rights reserved."
}
